version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
  
  database:
    image: postgres:13.4
    environment:
      - POSTGRES_PASSWORD=1amr00t
      - POSTGRES_USER=r00t
    volumes:
      - db_data_rentalx:/var/lib/postgresql/data
    network_mode: host
  
volumes:
  db_data_rentalx: